apiVersion: v1
kind: Secret
metadata:
  name: chi-user-passwords
  namespace: clickhouse
type: Opaque
stringData:
  admin_pass: "adminpass123"
  dev_pass: "dev1pass123"
  readonly_pass: "ReadOnlyPass"