apiVersion: v1
kind: Secret
metadata:
  name: chi-user-passwords
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.users }}
  {{ $key }}_pass: "{{ $val.password }}"
  {{- end }}